### ISSUE TITLE
Benchmark lit hydration vs. normal lit rendering

### ISSUE THREAD

**Issue by straversi** [PolymerLabs/lit-ssr#18]
Let's benchmark hydration of pre-rendered html using lit-html VS. rendering of the same page using normal lit-html. This can give us insights on the costs of the hashing scheme and other additions made for hydration.

**Comment by sorvell** [comment]
Included in https://github.com/PolymerLabs/lit-ssr/pull/56

Hydration is about **25% faster** than client rendering for the mail benchmark.
